Repository devops-ia/helm-opencti, pull requests merged in 2024-08, with the labels that each got.

#24 [opencti] new release: 6.2.13
  charts/opencti/Chart.yaml
Labels: auto-pr-bump-version

#25 Allow initContainer images to be pulled from private registry
  charts/opencti/templates/server/deployment.yaml
  charts/opencti/templates/tests/test-connection.yaml
  charts/opencti/templates/worker/deployment.yaml
Labels: enhancement

#28 [opencti] upgrade minor dependencies (2024-08-19)
  charts/opencti/Chart.yaml
  charts/opencti/README.md
Labels: auto-pr-bump-version

#30 [opencti] new release: 6.2.15
  charts/opencti/Chart.yaml
Labels: auto-pr-bump-version

#31 [opencti] upgrade minor dependencies (2024-08-26)
  charts/opencti/Chart.yaml
  charts/opencti/README.md
Labels: auto-pr-bump-version

#33 fix: pod and deployment annotations
  charts/opencti/ci/ci-values.yaml
  charts/opencti/templates/connector/deployment.yaml
  charts/opencti/values.yaml
Labels: bug

#39 fix: oras push helm sign for artifacthub
  .github/workflows/release.yaml
  charts/opencti/artifacthub-repo.yml
Labels: bug

#42 fix: release name on ready-checker
  charts/opencti/templates/server/deployment.yaml
  charts/opencti/templates/worker/deployment.yaml
Labels: bug

#47 feat: allow volumes on server and worker
  charts/opencti/README.md
  charts/opencti/templates/connector/deployment.yaml
  charts/opencti/templates/server/deployment.yaml
  charts/opencti/templates/worker/deployment.yaml
  charts/opencti/values.yaml
Labels: bug, enhancement

#37 Issue#36: check for OPENCTI_TOKEN
  charts/opencti/templates/connector/deployment.yaml
  charts/opencti/templates/worker/deployment.yaml
Labels: bug

#49 [opencti] new release: 6.2.16
  charts/opencti/Chart.yaml
Labels: auto-pr-bump-version

#51 [opencti] new release: 6.2.18
  charts/opencti/Chart.yaml
Labels: auto-pr-bump-version
